Removed padding
EkstraBladetUdvikling/eb-designsystem pull request #121
Opened 2021-05-27 11:28 UTC by mbjedk

2021-06-09 08:57 UTC, tegner requested changes

2021-06-09 08:57 UTC, tegner commented on src/components/horizontalScroll/HorizontalScroll.svelte
> +    if (listLength === scrollItemContainer.children) return;
De kan da aldrig blive true? 
skal det ikke være 
`if (listLength === scrollItemContainer.children.length)`
ellers forsøger du at matche et tal med et array

2021-06-09 08:57 UTC, tegner commented on src/components/tooltip/tooltip.css
> +  font-family: var(--fontfamily--secondary);
burde vi ikke slette works fra designsystemet? er der nogle steder vi skal bruge det længere?

2021-06-09 08:59 UTC, mbjedk commented on src/components/horizontalScroll/HorizontalScroll.svelte
> +    if (listLength === scrollItemContainer.children) return;
Nej, det ser mærkeligt ud.

2021-06-09 09:23 UTC, mbjedk commented on src/components/tooltip/tooltip.css
> +  font-family: var(--fontfamily--secondary);
I super artikel tror jeg

2021-06-09 11:18 UTC, tegner approved these changes

2021-06-09 11:18 UTC, tegner commented on src/components/horizontalScroll/HorizontalScroll.svelte
> +    const containerBBox = scrollContainer.getBoundingClientRect();
beat box? :P

2021-06-09 11:20 UTC, mbjedk commented on src/components/horizontalScroll/HorizontalScroll.svelte
> +    const containerBBox = scrollContainer.getBoundingClientRect();
BoomBox

2021-06-10 12:23 UTC, MathiasNordby commented on src/components/toggler/Toggler.svelte
> +    <Icon className="margin-s--rl" bind:name width="20" on:click={toggle} style="cursor: pointer;" />
Kan style="cursor: pointer;" ikke flyttes til toggle.css så CSS'en er adskildt?

2021-06-10 12:24 UTC, MathiasNordby commented on src/components/toggler/Toggler.svelte
> +    <Icon className="margin-s--rl" bind:name width="20" on:click={toggle} style="cursor: pointer;" />
nevermind, det er så fint beskrevet i designsystemet :p

2021-06-15 06:45 UTC, merged