Icons
EkstraBladetUdvikling/eb-designsystem pull request #129
Opened 2021-06-23 12:28 UTC by MathiasNordby

Ikoner er splittet op i Piktogrammer og Emojis (for at gøre det nemmere for kommende ikoner/opgaver til Shark)
- Piktogrammer (nuværende ikoner = simple fill ikoner)
- Emojis (feks ekstrabladet.svg = ikoner med statiske farver på stroke/fill)

- Emojis er sat op til auto build ligesom nuværende Piktogrammer.

2021-06-23 12:30 UTC, tcarlsen commented
sorry. men jeg bryder mig virkelig ikke om den navngivning.. Piktogrammer og emojies

2021-06-23 12:32 UTC, tegner commented
@tcarlsen det skal være noget der beskriver den basale forskel på de to typer - og der er piktogrammer i hvert fald meget sigende, hvis du har et mere rammende ord for nogle af dem må du byde ind med dem

2021-06-28 08:00 UTC, tcarlsen requested changes

2021-06-28 08:00 UTC, tcarlsen commented on docs_src/components/Icon.svelte
> +<p>Icons are simple and dynamic only made with fill like <a href="https://fontawesome.com/" target="_blank">Font Awesome</a> icons. Fill has the value currentColor and makes it possible to add the de
synes ikke det nødvendigt at give fontawesome et shoutout her. gør det ikke svære at forstå, hvis undladt

2021-06-28 08:02 UTC, MathiasNordby commented on docs_src/components/Icon.svelte
> +<p>Icons are simple and dynamic only made with fill like <a href="https://fontawesome.com/" target="_blank">Font Awesome</a> icons. Fill has the value currentColor and makes it possible to add the de
Alright, det var tiltænkt til eksterne feks Jacques der får linket om lidt til vores doc :)

2021-06-28 09:20 UTC, tcarlsen approved these changes

2021-06-28 09:30 UTC, merged